name: Keep-Alive

on:
  schedule:
    - cron: '*/10 * * * *' # Run every 10 minutes
  workflow_dispatch: # Enable manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: |
          curl -s https://campuslance.onrender.com/ping
